name = "vps-status"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[[ d1_databases ]]
binding = "DB"
database_name = "vps-monitor-db"
database_id = "87a1c09c-c16e-4acd-951a-82a4aa22e22b"

[triggers]
crons = ["* * * * *"]
